apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupod2
  name: ashupod2
spec:
  containers:
  - image: alpine
    name: ashupod2
    command: ["/bin/sh","-c","ping google.com"]  # here command is gonna replace parent process by entrypoint 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
