apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashudb
  name: ashudb
  namespace: ashuns
spec:
  containers:
  - image: mysql
    name: ashudb
    env: # to define env variable   --same as  docker run -e MYSQL_ROOT_PASSWORD=cisco123 
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
       secretKeyRef:
        name: mydbsec
        key: "y"
    ports:
    - containerPort: 3306
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
